server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: api
          uri: http://localhost:8081/
          predicates:
            - Path=/saidas/**, /entradas/**, /balanco/**