server:
  port: 8080
spring:
  application:
    name: auth
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 4c121263e1964b35431f
            clientSecret: c1cf94990f8519cb8a772d8e4893b1002b448f8b